version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=letalkserver
      - POSTGRES_PASSWORD=letalkserver
      - POSTGRES_DB=letalkserver
    volumes:
      - letalkserver_pg_data:/bitnami/postgresql

volumes:
  letalkserver_pg_data: